apiVersion: v1
kind: Service
metadata:
  name: logs-producer
  namespace: default
spec:
  # type: LoadBalancer | ClusterIP | NodePort
  selector:
    app: logs-producer
  ports:
    - name: http
      port: 4000 # service port
      protocol: TCP
      targetPort: 4000 # container port
